### ISSUE TITLE
When use with capistrano, get  incompatible library version error.

### ISSUE THREAD

**Issue by zw963** [RubyCrypto/ed25519#38]
```
cap aborted!
LoadError: incompatible library version - ed25519-1.3.0/lib/ed25519_ref10.so
<internal:ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
ed25519-1.3.0/lib/ed25519.rb:35:in `<module:Ed25519>'
ed25519-1.3.0/lib/ed25519.rb:9:in `<top (required)>'
<internal:ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/common/Stocks/marketbet_crawler/Capfile:6:in `<top (required)>'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
ruby/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
capistrano-3.17.1/lib/capistrano/application.rb:14:in `run'
bin/../app/capistrano/gems/capistrano-3.17.1/bin/cap:3:in `<main>'
```

Thanks

**Comment by tarcieri** [comment]
This seems like you compiled `ed25519_ref10.so` on a different host and then tried to relocate it

**Comment by zw963** [comment]
> This seems like you compiled `ed25519_ref10.so` on a different host and then tried to relocate it

I consider is no, i compile and install this gem in my local laptop, and use it here too.

**Comment by tarcieri** [comment]
It sounds like you're building a binary on your local laptop and trying to deploy it somewhere?

There is an incompatibility between the binary you're building and the host you're deploying it on. That's a general environmental issue which has nothing to do in this crate in particular, and will be problematic with any native extension.

**Comment by zw963** [comment]
> It sounds like you're building a binary on your local laptop and trying to deploy it somewhere?

AFAIK, when use `ed25519` with `capstrano`, it just for ssh login use ~/.ssh/id_ed25519, right?

so, what you means is, the deploying host must use same version with my local laptop?

But, i can always ssh login to deploying  host use ed25519 successful use ssh command directly, no any  incompatible issue.

**Comment by tarcieri** [comment]
This has nothing to do with Capistrano or SSH.

The problem is this:

```
LoadError: incompatible library version - ed25519-1.3.0/lib/ed25519_ref10.so
```

This gem is a library which implements a cryptographic primitive, the Ed25519 digital signature system, using a native extension.

Somehow you are building a version of that native extension which is incompatible with the Ruby version that you're using, which makes it sound like you're building the native extension with one Ruby version and/or environment and trying to copy it around and use it with another.

That won't work. You need to build it with the same Ruby version in the same environment you expect to deploy in.

Not having more information, I can't tell you exactly where that's happening, only that it's completely unrelated to this particular library, and has something to do with your environment.

**Comment by zw963** [comment]
Thanks, i found the issue, it seem like compile for 3.1.0 not works with 3.1.2
